[package]
name = "ss58-org"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
blake2 = "0.10.2"
hex = "0.4.3"
js-sys = "0.3.56"
yew = "0.19.3"

[dependencies.web-sys]
version = "0.3.56"
features = ["Clipboard", "Document", "HtmlInputElement", "Navigator", "Window"]
